<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="instance-1" failures="1" tests="1" name="Test(failed)" time="0.04" errors="0" timestamp="04 Jun 2022 13:42:18 GMT">
  <testcase classname="com.TestNg.learn.Surefile_testng" name="testingSurefire" time="0.01">
    <failure type="java.lang.AssertionError" message="This is the 2nd failed test">
      <![CDATA[java.lang.AssertionError: This is the 2nd failed test
at com.TestNg.learn.Surefile_testng.testingSurefire(Surefile_testng.java:16)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testingSurefire -->
  <testcase classname="com.TestNg.learn.Surefile_testng" name="passingTest" time="0.0">
    <ignored/>
  </testcase> <!-- passingTest -->
</testsuite> <!-- Test(failed) -->
